// lib/data.ts
import type { Zone, Unit, Alert, Message, User, NotificationType } from "./types"

// Sample zones data
export const zones: Zone[] = [
  {
    id: "zone-1",
    name: "Industrial Park",
    status: "normal",
    location: { lat: 51.505, lng: -0.09 },
    unitsCount: 12,
    activeUnits: 12,
    lastUpdated: "2023-04-10T14:30:00Z",
    consumption: 87.5,
    capacity: 95,
  },
  {
    id: "zone-2",
    name: "Downtown District",
    status: "warning",
    location: { lat: 51.51, lng: -0.1 },
    unitsCount: 8,
    activeUnits: 7,
    lastUpdated: "2023-04-10T15:45:00Z",
    consumption: 65.2,
    capacity: 70,
  },
  {
    id: "zone-3",
    name: "Residential Area",
    status: "critical",
    location: { lat: 51.515, lng: -0.09 },
    unitsCount: 15,
    activeUnits: 12,
    lastUpdated: "2023-04-10T16:20:00Z",
    consumption: 92.8,
    capacity: 95,
  },
  {
    id: "zone-4",
    name: "Shopping Complex",
    status: "normal",
    location: { lat: 51.52, lng: -0.08 },
    unitsCount: 6,
    activeUnits: 6,
    lastUpdated: "2023-04-10T17:10:00Z",
    consumption: 45.3,
    capacity: 80,
  },
  {
    id: "zone-5",
    name: "Tech Park",
    status: "inactive",
    location: { lat: 51.5, lng: -0.08 },
    unitsCount: 10,
    activeUnits: 0,
    lastUpdated: "2023-04-09T09:15:00Z",
    consumption: 0,
    capacity: 90,
  },
  {
    id: "zone-6",
    name: "Hospital Complex",
    status: "normal",
    location: { lat: 51.51, lng: -0.085 },
    unitsCount: 4,
    activeUnits: 4,
    lastUpdated: "2023-04-10T18:30:00Z",
    consumption: 72.1,
    capacity: 85,
  },
  {
    id: "zone-7",
    name: "University Campus",
    status: "warning",
    location: { lat: 51.525, lng: -0.095 },
    unitsCount: 7,
    activeUnits: 6,
    lastUpdated: "2023-04-10T19:45:00Z",
    consumption: 78.9,
    capacity: 85,
  },
]

// Sample units data
export const units: Unit[] = [
  {
    id: "unit-1",
    name: "Unit A-1",
    zoneId: "zone-1",
    status: "normal",
    level: 85,
    capacity: 100,
    lastRefilled: "2023-04-05T10:30:00Z",
    estimatedDaysRemaining: 12,
    address: "123 Industrial Ave, Block A",
    type: "commercial",
  },
  {
    id: "unit-2",
    name: "Unit A-2",
    zoneId: "zone-1",
    status: "normal",
    level: 78,
    capacity: 100,
    lastRefilled: "2023-04-06T11:45:00Z",
    estimatedDaysRemaining: 10,
    address: "125 Industrial Ave, Block A",
    type: "commercial",
  },
  {
    id: "unit-3",
    name: "Unit B-1",
    zoneId: "zone-2",
    status: "warning",
    level: 35,
    capacity: 80,
    lastRefilled: "2023-03-28T09:15:00Z",
    estimatedDaysRemaining: 4,
    address: "45 Downtown Street, Block B",
    type: "commercial",
  },
  {
    id: "unit-4",
    name: "Unit C-1",
    zoneId: "zone-3",
    status: "critical",
    level: 15,
    capacity: 120,
    lastRefilled: "2023-03-25T14:20:00Z",
    estimatedDaysRemaining: 1,
    address: "78 Residential Road, Block C",
    type: "residential",
  },
  {
    id: "unit-5",
    name: "Unit D-1",
    zoneId: "zone-4",
    status: "normal",
    level: 92,
    capacity: 100,
    lastRefilled: "2023-04-08T16:30:00Z",
    estimatedDaysRemaining: 14,
    address: "12 Shopping Plaza, Block D",
    type: "commercial",
  },
  {
    id: "unit-6",
    name: "Unit E-1",
    zoneId: "zone-5",
    status: "inactive",
    level: 0,
    capacity: 80,
    lastRefilled: "2023-03-15T10:00:00Z",
    estimatedDaysRemaining: 0,
    address: "56 Tech Park Road, Block E",
    type: "industrial",
  },
  {
    id: "unit-7",
    name: "Unit F-1",
    zoneId: "zone-6",
    status: "normal",
    level: 75,
    capacity: 150,
    lastRefilled: "2023-04-07T08:45:00Z",
    estimatedDaysRemaining: 9,
    address: "34 Hospital Street, Block F",
    type: "medical",
  },
  {
    id: "unit-8",
    name: "Unit G-1",
    zoneId: "zone-7",
    status: "warning",
    level: 40,
    capacity: 100,
    lastRefilled: "2023-03-30T11:20:00Z",
    estimatedDaysRemaining: 5,
    address: "89 University Road, Block G",
    type: "educational",
  },
  {
    id: "unit-9",
    name: "Unit A-3",
    zoneId: "zone-1",
    status: "normal",
    level: 82,
    capacity: 100,
    lastRefilled: "2023-04-04T13:15:00Z",
    estimatedDaysRemaining: 11,
    address: "127 Industrial Ave, Block A",
    type: "commercial",
  },
  {
    id: "unit-10",
    name: "Unit B-2",
    zoneId: "zone-2",
    status: "normal",
    level: 68,
    capacity: 80,
    lastRefilled: "2023-04-02T10:30:00Z",
    estimatedDaysRemaining: 8,
    address: "47 Downtown Street, Block B",
    type: "commercial",
  },
  {
    id: "unit-11",
    name: "Unit C-2",
    zoneId: "zone-3",
    status: "warning",
    level: 30,
    capacity: 120,
    lastRefilled: "2023-03-29T15:45:00Z",
    estimatedDaysRemaining: 3,
    address: "80 Residential Road, Block C",
    type: "residential",
  },
  {
    id: "unit-12",
    name: "Unit C-3",
    zoneId: "zone-3",
    status: "critical",
    level: 10,
    capacity: 100,
    lastRefilled: "2023-03-26T09:00:00Z",
    estimatedDaysRemaining: 1,
    address: "82 Residential Road, Block C",
    type: "residential",
  },
]

// Sample alerts data
export const alerts: Alert[] = [
  {
    id: "alert-1",
    unitId: "unit-4",
    zoneId: "zone-3",
    type: "critical",
    message: "Critical gas level detected. Immediate refill required.",
    timestamp: "2023-04-10T08:15:00Z",
    acknowledged: false,
  },
  {
    id: "alert-2",
    unitId: "unit-12",
    zoneId: "zone-3",
    type: "critical",
    message: "Critical gas level detected. Immediate refill required.",
    timestamp: "2023-04-10T09:30:00Z",
    acknowledged: false,
  },
  {
    id: "alert-3",
    unitId: "unit-3",
    zoneId: "zone-2",
    type: "warning",
    message: "Low gas level detected. Schedule refill within 4 days.",
    timestamp: "2023-04-10T10:45:00Z",
    acknowledged: true,
  },
  {
    id: "alert-4",
    unitId: "unit-8",
    zoneId: "zone-7",
    type: "warning",
    message: "Low gas level detected. Schedule refill within 5 days.",
    timestamp: "2023-04-10T11:20:00Z",
    acknowledged: false,
  },
  {
    id: "alert-5",
    unitId: "unit-11",
    zoneId: "zone-3",
    type: "warning",
    message: "Low gas level detected. Schedule refill within 3 days.",
    timestamp: "2023-04-10T12:10:00Z",
    acknowledged: true,
  },
  {
    id: "alert-6",
    unitId: "unit-6",
    zoneId: "zone-5",
    type: "system",
    message: "Connection lost with unit. Check device status.",
    timestamp: "2023-04-09T14:30:00Z",
    acknowledged: true,
  },
  {
    id: "alert-7",
    unitId: "unit-1",
    zoneId: "zone-1",
    type: "info",
    message: "Scheduled maintenance completed successfully.",
    timestamp: "2023-04-08T16:45:00Z",
    acknowledged: true,
  },
  {
    id: "alert-8",
    unitId: "unit-7",
    zoneId: "zone-6",
    type: "info",
    message: "Firmware update available for this unit.",
    timestamp: "2023-04-09T09:15:00Z",
    acknowledged: false,
  },
]

// Sample messages data
export const messages: Message[] = [
  {
    id: "msg-1",
    zoneId: "zone-3",
    sender: "system",
    content: "Critical alert: Two units in this zone require immediate attention.",
    timestamp: "2023-04-10T08:30:00Z",
    read: true,
  },
  {
    id: "msg-2",
    zoneId: "zone-3",
    sender: "user",
    content: "Dispatching maintenance team to check critical units.",
    timestamp: "2023-04-10T08:45:00Z",
    read: true,
  },
  {
    id: "msg-3",
    zoneId: "zone-3",
    sender: "system",
    content: "Maintenance team ETA: 30 minutes.",
    timestamp: "2023-04-10T08:50:00Z",
    read: true,
  },
  {
    id: "msg-4",
    zoneId: "zone-3",
    sender: "user",
    content: "Please prepare refill for units C-2 and C-3.",
    timestamp: "2023-04-10T09:15:00Z",
    read: true,
  },
  {
    id: "msg-5",
    zoneId: "zone-3",
    sender: "system",
    content: "Refill scheduled for units C-2 and C-3 at 11:00 AM.",
    timestamp: "2023-04-10T09:20:00Z",
    read: true,
  },
  {
    id: "msg-6",
    zoneId: "zone-3",
    sender: "user",
    content: "Confirmed. Please notify residents about the scheduled refill.",
    timestamp: "2023-04-10T09:25:00Z",
    read: true,
  },
  {
    id: "msg-7",
    zoneId: "zone-3",
    sender: "system",
    content: "Notifications sent to all residents in affected units.",
    timestamp: "2023-04-10T09:30:00Z",
    read: true,
  },
  {
    id: "msg-8",
    zoneId: "zone-2",
    sender: "system",
    content: "Warning: Unit B-1 requires refill within 4 days.",
    timestamp: "2023-04-10T10:45:00Z",
    read: false,
  },
  {
    id: "msg-9",
    zoneId: "zone-7",
    sender: "system",
    content: "Warning: Unit G-1 requires refill within 5 days.",
    timestamp: "2023-04-10T11:20:00Z",
    read: false,
  },
]

// Sample user data
export const currentUser: User = {
  id: "user-1",
  name: "John Doe",
  email: "john.doe@xpressgas.com",
  role: "Administrator",
  avatar: "/placeholder.svg?height=40&width=40",
  lastLogin: "2023-04-10T08:00:00Z",
}

// Sample notifications
export const notifications: NotificationType[] = [
  {
    id: 'notif-1',
    title: 'Critical Alert',
    message: 'Unit C-1 in Residential Area requires immediate refill',
    type: 'critical',
    timestamp: '2023-04-10T08:15:00Z',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Critical Alert',
    message: 'Unit C-3 in Residential Area requires immediate refill',
    type: 'critical',
    timestamp: '2023-04-10T09:30:00Z',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Warning Alert',
    message: 'Unit B-1 in Downtown District requires refill within 4 days',
    type: 'warning',
    timestamp: '2023-04-10T10:45:00Z',
    read: true,
  },
  {
    id: 'notif-4',
    title: 'Warning Alert',
    message: 'Unit G-1 in University Campus requires refill within 5 days',
    type: 'warning',
    timestamp: '2023-04-10T11:20:00Z',
    read: false,
  },
  {
    id: 'notif-5',
    title: 'System Message',
    message: 'Connection lost with Unit E-1 in Tech Park',
    type: 'system',
    timestamp: '2023-04-09T14:30:00Z',
    read:\
